CREATE TABLE IF NOT EXISTS stock_info (
    id          INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(16) NOT NULL,
    name        VARCHAR(64) NOT NULL,
    industry    VARCHAR(64),
    create_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
